"""empty message

Revision ID: 4d598145f01d
Revises: 
Create Date: 2021-09-05 21:23:47.580356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d598145f01d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(precision=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_num', sa.String(length=64), nullable=True),
    sa.Column('model_number', sa.String(length=64), nullable=True),
    sa.Column('purchase_date', sa.String(length=64), nullable=True),
    sa.Column('odometer', sa.Float(precision=64), nullable=True),
    sa.Column('vehicle_type', sa.String(length=64), nullable=True),
    sa.Column('unit_price', sa.Float(precision=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
