"""empty message

Revision ID: d8b9497338ba
Revises: 
Create Date: 2021-09-07 02:21:52.438471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b9497338ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False, auto_increment=True),
    sa.Column('vid', sa.Integer(), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.Column('book_duration', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_odo', sa.Float(), nullable=True),
    sa.Column('end_odo', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('additional_fee', sa.Float(), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_cid'), 'transactions', ['cid'], unique=False)
    op.create_index(op.f('ix_transactions_vid'), 'transactions', ['vid'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('balance', sa.Float(precision=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_num', sa.String(length=64), nullable=True),
    sa.Column('model_number', sa.String(length=64), nullable=True),
    sa.Column('purchase_date', sa.String(length=64), nullable=True),
    sa.Column('odometer', sa.Float(precision=64), nullable=True),
    sa.Column('vehicle_type', sa.String(length=64), nullable=True),
    sa.Column('unit_price', sa.Float(precision=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_transactions_vid'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_cid'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
